services:
  fluxo:
    build:
      context: ./fluxo 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  gateway:
    build:
      context: ../
      dockerfile: ./remote/gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok
    depends_on:
      - fluxo
      - gateway
    ports:
      - "4040:4040"
    env_file:
      - path: ../.env
    command:
      - "http"
      - "gateway:8080"

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: chatbot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
